include mk/version.mk
include mk/cross.mk
include mk/all.mk
include mk/pkg.mk
include mk/doc.mk
include mk/dotnet.mk
include mk/format.mk
include mk/cdn.mk
include mk/llvm.mk
include mk/debstrap.mk
include mk/cfg.mk
include mk/tool.mk
include mk/src.mk
include mk/libc.mk
include mk/var.mk
include mk/docker.mk
include mk/py.mk
include mk/clean.mk
include mk/ts.mk
include mk/debug.mk
include mk/boot.mk
include mk/dir.mk
include mk/ref.mk
include mk/rule.mk
include mk/merge.mk
include mk/squid.mk
include mk/rust.mk
include mk/patch.mk
include mk/install.mk
