include mk/var.mk
include mk/version.mk
include mk/dir.mk
include mk/tool.mk
include mk/src.mk
include mk/all.mk
include mk/format.mk
include mk/doc.mk
include mk/rule.mk
include mk/dotnet.mk
include mk/install.mk
include mk/merge.mk
