<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- <OutputType>Exe</OutputType> -->
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>TQL</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="lib/TQL.fs" />
    <Compile Include="lib/FileTree.fs" />
    <Compile Include="lib/AST.fs" />
    <Compile Include="lib/Storage.fs" />
  </ItemGroup>
</Project>
